### ISSUE TITLE
Add WorkInProgress story

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#163]
The WorkInProgress component already exists but there's no story for it in storybook.

In the `stories` folder add a file named `WorkInProgress.stories.tsx`

Using the `Header.stories.tsx` file as a template, adapt the contents of that file for the WorkInProgress component.

The WorkInProgress component takes no props.

Use the command `yarn storybook` to run the story on localhost and check that component is visible in storybook.

**Comment by hariscs** [comment]
assign this to me

**Comment by EmmaDawsonDev** [comment]
Hi @hariscs As it’s hacktoberfest we want many different contributors to have a chance at taking part. Therefore we’re limiting issues to max two at one time. I hope you understand. Please finish the two already assigned issues and then we can assign more.

**Comment by hariscs** [comment]
I'll finish the assigned one soon

**Comment by MarkusEicher** [comment]
Hi dear maintainers. I already applied for another issue. If you don't mind, I would be interested to have this one assigned to me too. Thanks!

**Comment by ctoffanin** [comment]
Hi @MarkusEicher, yes go ahead.

**Comment by MarkusEicher** [comment]
Hi there. Just a ping that I'm still working on the issue. First try was a fail. The story didn't appear as expected.

**Comment by ctoffanin** [comment]
No worries, take your time. Let us know if you need any help!

**Comment by MarkusEicher** [comment]
Thanks a lot for the support. Appreciate it. At this point I need to dig into it again. Will do that later this day. If it still won't work, I will be glad to reach out to you or have the issue reassigned to another contributor.

**Comment by EmmaDawsonDev** [comment]
Hi Markus! Take as long as you need on your issues, there's no pressure. Open source is as much about learning new things as it is making pull requests. And if you get stuck with anything just let us know and one of us will help you out.

**Comment by MarkusEicher** [comment]
Hello dear maintainers. 

I have an issue with my gitignore file when following the steps in the CONTRIBUTING.md. After forking the repo and cloning it locally i added the upstream to the original repository and all went well. Now, after running yarn install there are two files listed as changed or untracked in Git. These are .yarnrc.yml which shows as untracked and yarn.lock which has changed.

> $ git status
On branch main
Your branch is up to date with 'origin/main'.

>Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        **modified:   yarn.lock**

>Untracked files:
  (use "git add <file>..." to include in what will be committed)
        **.yarnrc.yml**

>no changes added to commit (use "git add" and/or "git commit -a")

While I'm pretty sure that .yarnrc.yml has to be excluded I added it to my local .gitignor file and unstaged it from Git. Where I am not sure what to do is with the yarn.lock file. This file needs to be tracked, I guess. What confuses me, is the fact that when I pull the remote origin and remote upstream like so: 

>marku@Grisu-Noty MINGW64 /c/Data/Forked-Projects/AccessibleWebDev (main)
$ git pull upstream main
From https://github.com/AccessibleForAll/AccessibleWebDev
>* branch            main       -> FETCH_HEAD
Already up to date.

>marku@Grisu-Noty MINGW64 /c/Data/Forked-Projects/AccessibleWebDev (main)
$ git pull origin main
From https://github.com/MarkusEicher/AccessibleWebDev
> * branch            main       -> FETCH_HEAD
Already up to date.

It now tells me up to date. I understand that because I did not already commit my local changes to my origin remote. The question now is if I can now checkout my local feature branch and start building the story or do I have to exclude the yarn.lock file first.

Sorry for the inconvenience but this is a little confusing for me as a newbie. If someone finds the time, I appreciate any support in this case. Thanks.

**Comment by ctoffanin** [comment]
Hi @MarkusEicher, you are running yarn version >= 2, right?

**Comment by MarkusEicher** [comment]
Hi Cristian @ctoffanin 

Yes. I'm running yarn version 3.2.3

**Comment by EmmaDawsonDev** [comment]
I think the differences may be coming because the project is running yarn 1 and they introduced the yarnrc.yml with version 2. It's something I need to look into. 

However, you are absolutely fine to create a branch and work on the feature with the files still there locally. Just when you do `git add ` be careful to only stage files that you've worked on (don't use `git add .` ). You can do this with `git add file1 file2` or `git add folderName`.

Hope that helps but if not let us know where you get stuck.

**Comment by MarkusEicher** [comment]
Good morning, Emma. Yes, that was what I expected to hear, and I will do exactly that. I was sure not to track yarnrc.yml but was not so sure about yarn.lock because this file is present in the upstream and has changed recently with PR181 after YuriDevAT added the a11y extension for Storybook. I understand now that the change in yarn.lock only is relevant, because this extends the functionality of the whole application. I will now finish my stories and then open the PR's. Thanks for your support.

**Comment by Y0rubaCoproducer** [comment]
Happy Sunday Emma,

I'd like to help with this.

Please let me know. Tuesday is my code day this week in case that may be an issue.
Thank you.
Kemmy

**Comment by MarkusEicher** [comment]
Hi @Y0rubaCoproducer. Hello maintainers. May I suggest the following proceudure. I'm currently working on this. If I struggle or it is not finished by Tuesday, then assign it to @Y0rubaCoproducer. Please let me know, if that is OK for you. Have a great Sunday y'all.

**Comment by Y0rubaCoproducer** [comment]
Hey Mark,
Absolutely. I am very new to this so I didn't grasp that this project is one person per issue. I'm really happy to help with anything so perhaps I'll read some papers/guides/instead of references and see if they can be improved in anyway.

Please take your time and good luck!! ✨
Kemmy

**Comment by ctoffanin** [comment]
Hi @MarkusEicher, no worries. Feel free to tell us if/when you want the issue to be unassigned from you. We'll assign it to @Y0rubaCoproducer then.

**Comment by MarkusEicher** [comment]
Thanks, Christian! 💚 Appreciate your patience. Will be done soon.

**Comment by EmmaDawsonDev** [comment]
@Y0rubaCoproducer Most often on open source projects each issue gets assigned to one person to avoid people doing unnecessary/duplicate work (unless people want to pair up on an issue). 

I will try to look through the project either this evening or early this week and see if there are more issues that I can add.

**Comment by MarkusEicher** [comment]
Hello community. I just started to finalize this issue. Just to let you know that it's still work in progress. Have a good day.
