### ISSUE TITLE
Footer GitHub icon opens in the same tab

### ISSUE THREAD

**Issue by MuhammadRabi** [AccessibleForAll/AccessibleWebDev#360]
**Describe the bug**
The Footer GitHub icon opens in the same tab.

**To Reproduce**
1. Go to the Homepage
2. Scroll down to the Footer
3. Click on GitHub Icon

**Expected behavior**
external links should be opened in a new tab

**Screenshots**
N.A.

**Additional context**
I would like to work on this if allowed

**Comment by EmmaDawsonDev** [comment]
Hi Muhammad, the link actually behaves as expected. Opening in a new tab/window is not the inbuilt expected behaviour and can cause screen reader users and people with cognitive impairments to get disoriented by the behaviour. As it is, it's possible for people to right click and choose to open in a new tab if they wish.

**Comment by MuhammadRabi** [comment]
Hi Emma, I didn't know that. I will close the issue then. 
Thank you!
